### ISSUE TITLE
教程呢，大师

### ISSUE THREAD

**Issue by Confucian-e** [qianyiwangmeng/goHomework#1]
大师，我是菜狗，整不来，给个教程

**Comment by qianyiwangmeng** [comment]
明天上午喊我，我手把手，视你为妹子


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianyiwangmeng/goHomework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月28日(星期六) 下午2:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianyiwangmeng/goHomework] 教程呢，大师 (Issue #1)





 
大师，我是菜狗，整不来，给个教程

**Comment by Confucian-e** [comment]
没得问题，环境已经装好了

**Comment by Confucian-e** [comment]
多谢大师细心指导，已经是成功浑水摸鱼过关成功

**Comment by qianyiwangmeng** [comment]
你都会了还要什么教程




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianyiwangmeng/goHomework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianyiwangmeng/goHomework] 教程呢，大师 (Issue #1)





 
Closed #1 as completed.
